spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/malldb
    username: malldbuser
    password: 1234

  # spring data JPA 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

# logging 설정
logging:
  level:
    sql: debug